### ISSUE TITLE
Any news about the GPT expended datasets?

### ISSUE THREAD

**Issue by ch3cook-fdu** [Ivan-Tang-3D/ViewRefer3D#2]
Thanks for the great work! Would the GPT-expended datasets for ScanRefer or Nr3D be open?

**Comment by Ivan-Tang-3D** [comment]
Sorry for the delay. Thanks for the issue. We are organizing the data and will release the part of Sr3D on the Oct. We will notify you when it is open sourced.

**Comment by ch3cook-fdu** [comment]
Thanks! That helps a lot. 

Yet, I have another question. Are all the linguistic datasets (i.e. ScanRefer, Nr3D, Sr3D) be rephrased and expaned with GPT-3, or, only Sr3D?

**Comment by Ivan-Tang-3D** [comment]
Yes, The all datasets are rephrased. We will release the rephrased data of Sr3D soon

**Comment by ch3cook-fdu** [comment]
Great many thanks! looking forward to the datasets!
