### ISSUE TITLE
"train.sh"problem

### ISSUE THREAD

**Issue by Morgansgun** [Ivan-Tang-3D/ViewRefer3D#3]
In the file"train.sh",there is " PATH_OF_SCANNET_FILE='./referit3d_3dvg/data/keep_all_points_with_global_scan_alignment.pkl'",line 2.
so what is the "keep_all_points_with_global_scan_alignment.pkl",when I open the folder data, I didn't find this file.How can I get it?

**Comment by Ivan-Tang-3D** [comment]
The file is created from this part: https://github.com/referit3d/referit3d/blob/eccv/referit3d/data/scannet/README.md
