### ISSUE TITLE
About how to make evaluation in the Scanrefer Datasets.

### ISSUE THREAD

**Issue by visualjason** [Ivan-Tang-3D/ViewRefer3D#6]
Hello,I have read your paper and found it very interesting how you adapted the MVT model for testing on ScanRefer.And I'm very interesting at how to transform a regression problem into a detection-like task and perform IoU (Intersection over Union) testing.

**Comment by Ivan-Tang-3D** [comment]
Thank you, Please Refer to this link https://github.com/sega-hsj/MVT_ScanRefer; They have stored the segmented objects as separate files.
